# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: meeting
  description: meeting list
  icon: pending
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ""
  preheading: ""
  heading: ""
  content: ""
  phone: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_image: /images/bg/aubergine_field.png
  preheading: Getting the Most out of Meetings
  heading: agendT: Leveraging Your Team's PRoductivity

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}



