# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: meeting
  description: meeting list
  icon: pending

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  sections:
      content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: Meetings are key to Team Productivity
  heading: Make the most of them with agendT


