# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: meeting
  description: meeting list
  icon: pending
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "meetings"
  hero:
    title: "meetings"
    background_image: "lime_gr_field.png"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
